import json
from textwrap import dedent
from typing import Any


def generate_python_code(schema: dict[str, Any], plan: dict[str, Any]) -> str:
    schema_json = json.dumps(schema, indent=2)
    plan_json = json.dumps(plan, indent=2)[:12000]
    return f'''#!/usr/bin/env python3
"""Synthetic insurance test payload generator.
Generated by the AI-assisted Synthetic Insurance Data Generator POC.
This script creates fake data only and never uses production records.
"""
import argparse
import csv
import json
import random
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

from faker import Faker
from jsonschema import Draft202012Validator, exceptions as jsonschema_exceptions

fake = Faker("en_US")
Faker.seed(4242)
random.seed(4242)

SCHEMA: dict[str, Any] = {schema_json}
GENERATION_PLAN: dict[str, Any] = {plan_json}
US_STATES = ["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","IA","ID","IL","IN","KS","KY","LA","MA","MD","ME","MI","MN","MO","MS","MT","NC","ND","NE","NH","NJ","NM","NV","NY","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VA","VT","WA","WI","WV","WY"]


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate synthetic insurance API payloads")
    parser.add_argument("--count", type=int, default=10)
    parser.add_argument("--format", choices=["json", "jsonl", "csv"], default="json")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    records = [generate_record(i) for i in range(max(1, args.count))]
    write_output(records, args.format, Path(args.output))


def generate_record(index: int) -> dict[str, Any]:
    # Generate from the normalized JSON Schema, then apply cross-field insurance rules.
    record = generate_value(SCHEMA, "", {{}})
    if not isinstance(record, dict):
        record = {{"value": record}}
    apply_business_rules(record, index)
    return record


def generate_value(schema: dict[str, Any], path: str, context: dict[str, Any]) -> Any:
    if not isinstance(schema, dict):
        return None
    if "enum" in schema:
        return random.choice(schema["enum"])
    typ = schema.get("type")
    if isinstance(typ, list):
        if "null" in typ and random.random() < 0.15:
            return None
        typ = next((t for t in typ if t != "null"), typ[0])
    if typ is None and "properties" in schema:
        typ = "object"
    if typ == "object":
        required = set(schema.get("required", []))
        obj = {{}}
        for name, child in schema.get("properties", {{}}).items():
            if name not in required and random.random() < 0.18:
                continue
            obj[name] = generate_value(child, join_path(path, name), obj)
        return obj
    if typ == "array":
        min_items = int(schema.get("minItems", 1))
        max_items = int(schema.get("maxItems", max(min_items, 3)))
        max_items = max(min_items, min(max_items, 5))
        return [generate_value(schema.get("items", {{"type": "string"}}), path + "[]", context) for _ in range(random.randint(min_items, max_items))]
    if typ in ("integer", "number"):
        return generate_number(path, schema, integer=(typ == "integer"))
    if typ == "boolean":
        return random.choice([True, False])
    return generate_string(path, schema)


def generate_string(path: str, schema: dict[str, Any]) -> str:
    name = path.lower()
    fmt = schema.get("format")
    if fmt == "date" or "date" in name:
        return (date.today() + timedelta(days=random.randint(-365, 365))).isoformat()
    if fmt == "date-time":
        return datetime.utcnow().replace(microsecond=0).isoformat() + "Z"
    if fmt == "email" or "email" in name:
        return fake.safe_email()
    if "phone" in name:
        return fake.numerify("###-###-####")
    if "state" in name:
        return random.choice(US_STATES)
    if "zip" in name or "postal" in name:
        return fake.postcode()
    if "address" in name:
        return fake.street_address()
    if "city" in name:
        return fake.city()
    if "firstname" in name or name.endswith(".first"):
        return fake.first_name()
    if "lastname" in name or name.endswith(".last"):
        return fake.last_name()
    if "name" in name:
        return fake.name()
    if "vin" in name:
        return fake.vin()
    if "policy" in name:
        return "POL-" + fake.bothify("########")
    if "claim" in name:
        return "CLM-" + fake.bothify("########")
    if "license" in name:
        return fake.bothify("?#######").upper()
    min_len = int(schema.get("minLength", 6))
    max_len = int(schema.get("maxLength", max(min_len, 24)))
    return fake.bothify("????-########")[:max(min_len, min(max_len, 16))]


def generate_number(path: str, schema: dict[str, Any], integer: bool) -> int | float:
    name = path.lower()
    minimum = schema.get("minimum", schema.get("exclusiveMinimum", 0 if any(k in name for k in ["premium", "limit", "deductible", "amount", "age", "year"]) else 1))
    maximum = schema.get("maximum", None)
    if maximum is None:
        if "deductible" in name:
            maximum = 5000
        elif "limit" in name:
            maximum = 1000000
        elif "premium" in name:
            maximum = 12000
        elif "year" in name:
            minimum, maximum = 1990, date.today().year + 1
        else:
            maximum = max(float(minimum) + 100, 1000)
    value = random.uniform(float(minimum), float(maximum))
    return int(round(value)) if integer else round(value, 2)


def apply_business_rules(record: dict[str, Any], index: int) -> None:
    # Common insurance date relationship: expiration after effective date, usually one year later.
    eff_path = find_key_path(record, "effectiveDate")
    exp_path = find_key_path(record, "expirationDate")
    if eff_path:
        eff = date.today() + timedelta(days=random.randint(-30, 90))
        set_path(record, eff_path, eff.isoformat())
        if exp_path:
            set_path(record, exp_path, (eff + timedelta(days=365)).isoformat())
    dob_path = find_key_path(record, "dateOfBirth")
    if dob_path:
        age = random.randint(18, 80)
        set_path(record, dob_path, (date.today() - timedelta(days=age * 365 + random.randint(0, 364))).isoformat())
    state_path = find_key_path(record, "state")
    if state_path:
        set_path(record, state_path, random.choice(US_STATES))
    ded_path = find_key_path(record, "deductible")
    lim_path = find_key_path(record, "coverageLimit") or find_key_path(record, "limit")
    if ded_path and lim_path:
        deductible = random.choice([250, 500, 1000, 2500, 5000])
        set_path(record, ded_path, deductible)
        set_path(record, lim_path, deductible + random.choice([25000, 50000, 100000, 250000, 500000]))
    premium_path = find_key_path(record, "premium")
    if premium_path:
        set_path(record, premium_path, round(random.uniform(250, 5000), 2))


def find_key_path(value: Any, target: str, base: list[Any] | None = None) -> list[Any] | None:
    base = base or []
    if isinstance(value, dict):
        for key, child in value.items():
            if key.lower() == target.lower():
                return base + [key]
            found = find_key_path(child, target, base + [key])
            if found:
                return found
    if isinstance(value, list):
        for i, child in enumerate(value):
            found = find_key_path(child, target, base + [i])
            if found:
                return found
    return None


def set_path(value: Any, path: list[Any], new_value: Any) -> None:
    node = value
    for part in path[:-1]:
        node = node[part]
    node[path[-1]] = new_value


def join_path(prefix: str, name: str) -> str:
    return f"{{prefix}}.{{name}}" if prefix else name


def flatten(record: dict[str, Any], prefix: str = "") -> dict[str, Any]:
    out = {{}}
    for key, value in record.items():
        full_key = f"{{prefix}}.{{key}}" if prefix else key
        if isinstance(value, dict):
            out.update(flatten(value, full_key))
        elif isinstance(value, list):
            out[full_key] = json.dumps(value)
        else:
            out[full_key] = value
    return out


def write_output(records: list[dict[str, Any]], output_format: str, output: Path) -> None:
    if output_format == "json":
        output.write_text(json.dumps(records, indent=2), encoding="utf-8")
    elif output_format == "jsonl":
        output.write_text("\\n".join(json.dumps(r) for r in records), encoding="utf-8")
    else:
        rows = [flatten(r) for r in records]
        fieldnames = sorted({{k for row in rows for k in row}})
        with output.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)


if __name__ == "__main__":
    main()
'''
